---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether asciiquarium is installed
      command: test -e /usr/local/bin/asciiquarium
      register: ASCIIQUARIUM_INSTALLED
      changed_when: False
      ignore_errors: True

    - name: Check OS version
      command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show ASCIIQuarium installed
      debug:
        var: ASCIIQUARIUM_INSTALLED

    - name: Show OS version
      debug:
        var: OS_VERSION
