---
name: Ansible Playbook
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            tasks/main.yml

      - name: Build CentOS7 image sudo installed
        run: docker build tests/. -t centos7sudo

      - name: Docker run CentOS7 image sudo installed
        run: sudo docker run -d -t --name=mycontainer centos7sudo

      - name: Show Ansible version
        run: ansible --version

      - name: Install Ansible galaxy roles
        run: ansible-galaxy install -r tests/roles/requirements.yml -p tests/roles

      - name: Execute ansible-playbook command
        run: ansible-playbook -i 'mycontainer,' -c docker tests/test.yml

      - name: Check idempotency
        run: ansible-playbook -i 'mycontainer,' -c docker tests/test.yml
